services:
  sql:
    image: mysql:8.4.2
    container_name: raintree-sql-stenmartin
    ports:
      # external: internal
      - 7890:3306
    volumes:
      - sql-volume:/var/lib/raintree/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    restart: on-failure
    logging:
      options:
        max-size: 10m
        max-file: 3
volumes:
  sql-volume: