DROP TABLE IF EXISTS insurance;
DROP TABLE IF EXISTS patient;

CREATE TABLE patient (
     _id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
     pn VARCHAR(11) DEFAULT NULL,
     first VARCHAR(15) DEFAULT NULL,
     last VARCHAR(25) DEFAULT NULL,
     dob DATE DEFAULT NULL,
     PRIMARY KEY (_id)
);

CREATE TABLE insurance (
   _id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
   patient_id INT(10) UNSIGNED NOT NULL,
   iname VARCHAR(40) DEFAULT NULL,
   from_date DATE DEFAULT NULL,
   to_date DATE DEFAULT NULL,
   PRIMARY KEY (_id),
   FOREIGN KEY (patient_id) REFERENCES patient(_id)
       ON DELETE CASCADE
       ON UPDATE CASCADE
);